site_name: holstein
repo_name: holstein
site_dir: public
docs_dir: ../docs
theme:
  language: ca
  name: material
  features:
    - navigation.instant
    - navigation.indexes
   # - navigation.sections
    - navigation.path
    - header.autohide
    - search.highlight
    - search.suggest
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - content.code.copy
    - content.action.edit

  icon:
    repo: fontawesome/brands/git-alt
    edit: material/pencil 
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - toc:                 
      permalink: true
plugins:
  - mkdocs-video
  - search:
      lang: 
        - es
        - en
  - git-authors
  - git-revision-date-localized:
      enable_creation_date: true
  - with-pdf:
      cover_logo: images/enunciat/diagrama-xarxa.png
      cover_subtitle: Solució exercici
      two_columns_level: 3
      output_path: document.pdf
nav:
  - Presentació: index.md
  - Documentació:
      - Apartado: documentacio/index.md
      - Sprint 1: 
        - Índex: documentacio/sprint1/test.md
      - Sprint 2:
        -Índex: documentacio/sprint2/test.md
  - Teoria GIT:
      - Git: git/git.md
