nav:
  - Presentació: index.md
  - Documentació:
      - Apartado: documentacio/index.md
      - Sprint 1: 
          - Índex: documentacio/sprint1/test.md
      - Sprint 2: 
          - Índex: documentacio/sprint1/test3.md
      - Sprint 3: 
          - Índex: documentacio/sprint1/test2.md
  - Teoria GIT:
      - Git: git/git.md
  - M01 Sistemas: 
      - Apartado: sistemas_docs/sistemas.md
      - Sistemas:
          - Docker: sistemas_docs/docker.md 
  - M02 Bases de datos:
      - Apartado: bbdd_docs/bbdd.md
      - Bases de datos: 
          - Script Inicial: bbdd_docs/script.md
          - Funcions: bbdd_docs/funcions.md  
          - Procedimientos: bbdd_docs/procedures.md 
          - Consultas: bbdd_docs/consultas.md 
  - M03 Programación: pr.md 
  - M04 Lenguaje de Marcas: ldm.md
  - M05 Entornos de Desarollo :
      - Apartado: entorns_docs/entorns.md 
      - Entornos de Desarollo:
          - Casos de uso: entorns_docs/casosdeuso.md 
          - Diagrama de clases: entorns_docs/diagramadeclases.md 
          - Diagrama Entidad-Relación: entorns_docs/diagramaER.md 


