site_name: Holstein
repo_name: git@gitlab.com:dax_mesapp_g16/g16_holstein.git
site_dir: public
docs_dir: ../docs
theme:
  language: es
  name: material
  features:
    - navigation.instant
    - navigation.indexes
   # - navigation.sections
    - navigation.path
    - header.autohide
    - search.highlight
    - search.suggest
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - content.code.copy
    - content.action.edit

  icon:
    repo: fontawesome/brands/git-alt
    edit: material/pencil 
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - toc:                 
      permalink: true


  - search:
      lang: 
        - es
        - en
  - git-authors
  - git-revision-date-localized:
      enable_creation_date: true
  - with-pdf:
      cover_logo: images/enunciat/diagrama-xarxa.png
      cover_subtitle: Solució exercici
      two_columns_level: 3
      output_path: document.pdf
nav:
  nav:
  - Presentació: index.md
  - Documentació:
      - Apartado: documentacio/index.md
      - Sprint 1: 
          - Índex: documentacio/sprint1/test.md
  - Teoria GIT:
      - Git: git/git.md
  - M01 Sistemas: 
      - Apartado: sistemas_docs/sistemas.md
      - Sistemas:
          - Docker: sistemas_docs/docker.md 
  - M02 Bases de datos:
      - Apartado: bbdd_docs/bbdd.md
      - Bases de datos: 
          - Script Inicial: bbdd_docs/script.md
          - Funcions: bbdd_docs/funcions.md  
          - Procedimientos: bbdd_docs/procedures.md 
          - Consultas: bbdd_docs/consultas.md 
  - M03 Programación: pr.md 
  - M04 Lenguaje de Marcas: ldm.md
  - M05 Entornos de Desarollo :
      - Apartado: entorns_docs/entorns.md 
      - Entornos de Desarollo:
          - Casos de uso: entorns_docs/casosdeuso.md 
          - Diagrama de clases: entorns_docs/diagramadeclases.md 
          - Diagrama Entidad-Relación: entorns_docs/diagramaER.md 

